package com.ss.skalkaadministrativemobile.model;

import com.ss.skalkaadministrativemobile.model.table.OrderColumns;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.UUID;

/**
 * Created by kan on 14.01.2015.
 */
public class Order extends HashMap<String, String> {

    private static final DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");

    public static final String[] COLUMN_NAMES = OrderColumns.columns();

    public Order() {
        super();
        setOrderDate(Calendar.getInstance().getTime());
        setNumber((int) Math.abs(UUID.nameUUIDFromBytes(this.toString().getBytes()).getLeastSignificantBits()));
    }

    private void put(OrderColumns column, String value) {
        put(column.cname().toLowerCase(), value);
    }

    public void setPrice(String price) {
        put(OrderColumns.PRICE, price);
    }


    /* values are generated by system and should be not set explicitly */

    private void setNumber(int number) {
        put(OrderColumns.NUMBER, String.valueOf(number));
    }
    private void setOrderDate(Date date) {
        put(OrderColumns.ORDER_DATE, dateFormat.format(date));
    }

    @Override
    public String toString() {
        StringBuilder strb = new StringBuilder();
        strb.append("Order : [");
        for (String key : keySet()) {
            strb.append(key);
            strb.append(": ");
            strb.append(get(key));
            strb.append("; ");
        }
        strb.append("]");
        return strb.toString();
    }
}
